version: 0.1
phases:
  install:
    commands:
      - npm install     
      - npm install --cwd "./lambda/src/alexa-interface" --prefix "./lambda/src/alexa-interface"    
      # alexa-news-stand
      # alexabucket1719
      # - aws s3 cp ./lambda/src/alexa-service/coverage s3://alexabucket1719/coverage --recursive
      - aws s3 cp ./models/schema.graphql s3://alexabucket1719/schema.graphql
      - aws cloudformation package --template-file template.yaml --s3-bucket alexabucket1719 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml